<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
<link rel="stylesheet" href="../../../common.css">
<script src="../../../common.js"></script>
<title>1. 例外処理とは</title>
</head>
<body>

<nav class="brcr">
<ol>
<li><a href="../">アクティビティ: Java言語の基礎</a></li>
<li>学習項目: [2] 例外処理</li>
<li><script>GetTitle()</script></li>
</ol>
</nav>

<h2><script>GetTitle()</script></h2>

<p>
<b>例外</b>とは実行時に生じるエラーの事で、ある処理を実行中に例外が生じたらその処理を中断してエラー処理を行う機能のことを「<b>例外処理</b>」と呼びます。
</p>
<p>
例外処理の書式は以下の通りです。
</p>

<div class="info">
<input type="checkbox"><b>例外処理の書式:</b>

<pre class="wrap">
   try
   {
   　 例外1〜Nが起きる可能性のある処理部
   }
   catch(例外その1){
   {
      例外1のエラー処理部
   }
   catch(例外その2){
   {
      例外2のエラー処理部   
   }
   ・・・
   catch(例外そのN){
   {
      例外Nのエラー処理部
   }
</pre>

</div>

<p>
まず「try」のカッコ内に例外が起きる可能性のある処理部を書きます。
</p>

<p>
次に例外が起きた時のエラー処理部を「catch」のカッコ内に書きます。
<br>
もし try の中にある処理で例外が生じたらその処理の実行を中止し、catchの中にジャンプしてエラー処理を実行します(エラー処理が終わっても try の中には戻りません)。
<br>
また上の例の様に catch を例外の種類ごとに複数並べることで、種類別にエラー処理することが出来ます。
</p>

<p>
この様に例外が起きてcatchの中に処理が移ることを<b>「例外が投げられた」</b>と言います。
</p>

<p>
この例外処理のメリットは「処理部」と「エラー処理部」を分けて書けることにあります。
<br>
一般的にエラー処理部は煩雑で見づらい事が多いので、取り敢えずエラー処理は後回しにして処理部だけ書くことで、すっきりと見やすいソースコードになります。
</p>
<p>
もう少し具体的に例外処理の例を見てみましょう。
<br>
次のソース 1 はファイルオープン時に指定したファイル(今回は hoge.txt )が存在しない時に投げられる例外処理です。
</p>

<p>
※ ファイルの<a href="../text03/page01.html">書き込み</a>と<a href="../text03/page01.html">読み込み</a>については次の学習項目で詳しく扱います。
</p>

<div class="info">
<input type="checkbox"><b>ソース1: ファイルオープンに失敗した時の例外処理 </b>

<pre class="wrap">
import java.io.FileReader;
import java.io.IOException;

public class Main
{
  public static void main(String[] args) {

     try{ 
         FileReader in = new FileReader( "hoge.txt" ); 
     } 
     catch( IOException e ) { 
         System.out.println( "入出力例外発生: "+e );
     }
  }
}
</pre>

</div>

<p>
try の中で FileReader クラスを使ってファイルをオープンしていますが、もしファイル(今回は hoge.txt )が無ければ IOException という名前の例外が生じます。
</p>

<p>
※ IOException については<a href="./page02.html">次のページ</a>で説明します
</p>

<p>
IOException 例外が生じると catch 内に処理が移って、エラーに関する情報が変数 e に入ります。
<br>
その e を println すると画面上には次のように表示されます。
</p>

<div class="info">
<input type="checkbox"><b>ソース1の実行結果 (hoge.txt が存在しない場合) : </b>

<pre class="wrap">
入出力例外発生: java.io.FileNotFoundException: hoge.txt (No such file or directory)
</pre>
</div>

<br>
<script>PreNext(1,2)</script>
</body>
</html>
